# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1co8jWKGpqnTGXPcveFMrrGpO92ZTR0lT
"""

!pip install streamlit
!streamlit run app.py