# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1co8jWKGpqnTGXPcveFMrrGpO92ZTR0lT
"""

!pip install streamlit
!streamlit run app.py

# Commented out IPython magic to ensure Python compatibility.
# # First, install streamlit in a Colab cell:
# !pip install streamlit
# 
# # Then, save your Streamlit code to a file and run it as a background process:
# %%writefile app.py
# # Paste your complete Streamlit code here (the same code you provided)
# 
# # Run the Streamlit app
# !streamlit run app.py &>/dev/null&